spring:
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  application:
    name: pfa_project
  datasource:
    url: jdbc:postgresql://localhost:5432/pfa_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver  # Explicit driver (recommended)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  # Pretty-print SQL
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Explicit dialect